name: gcc

# Trigger on pushes to all branches and for all pull-requests
on: [push, pull_request]

env:
  CMAKE_VERSION: 3.16.2
  NINJA_VERSION: 1.10.0

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        # GCC-9
        # - {
        #     name: "Linux GCC 9",
        #     os: ubuntu-latest,
        #     build_type: Release,
        #     cxx: "g++-9"
        #   }

        # AppleClang
        - {
            name: "macOS Clang",
            os: macos-latest,
            build_type: Release,
            cxx: "clang++",
          }

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Building
      shell: bash
      working-directory: ${{ env.HOME }}
      env:
        CXX: ${{ matrix.config.cxx }}
        CC: clang
      run: |
        export PATH=`pwd`:$PATH
        echo $HOME
        ls -l
        pwd
        mkdir -p gcc_all/build
        cd gcc_all
        curl -L https://ftpmirror.gnu.org/gcc/gcc-10.1.0/gcc-10.1.0.tar.xz | tar xf -
        cd gcc-10.1.0
        ./contrib/download_prerequisites
        cd ../build
        echo "path changed"
        ../gcc-10.1.0/configure --prefix=/usr/local/gcc-10 --enable-checking=release --enable-languages=c,c++ --enable-silent-rules --disable-multilib --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk --program-suffix=-10
        make -j > /dev/null
        echo "build finished"
        sudo mkdir -p /usr/local/gcc-10
        sudo chmod 0777 /usr/local/gcc-10
        ls -l /usr/local        
        make install-strip
        tar -cJf ../../gcc-10.tar.xz -C /usr/local/gcc-10 /usr/local/gcc-10

    - uses: actions/upload-artifact@v2
      with:
        name: gcc
        path: gcc-10.tar.xz

